### ISSUE TITLE
Problem: fits fails on Centos/RedHat with mkv files

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/am-packbuild#172]
Manual test (Redhat):
<pre>
[archivematica@alder ~]$ ng edu.harvard.hul.ois.fits.Fits -i . -o /tmp/mamedin_delete/
java.lang.NoClassDefFoundError: Could not initialize class edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfoNativeWrapper
	at edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo.<init>(MediaInfo.java:104)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:139)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:77)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:210)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:128)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:117)
	at edu.harvard.hul.ois.fits.Fits.main(Fits.java:258)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)
</pre>

/var/log/messages errors:

<pre>
May  2 12:50:18 alder fits-ngserver.sh: #
May  2 12:50:18 alder fits-ngserver.sh: # A fatal error has been detected by the Java Runtime Environment:
May  2 12:50:18 alder fits-ngserver.sh: #
May  2 12:50:18 alder fits-ngserver.sh: #  SIGSEGV (0xb) at pc=0x00007f8bfcb4533d, pid=48810, tid=0x00007f8bcc1a4700
May  2 12:50:18 alder fits-ngserver.sh: #
May  2 12:50:18 alder fits-ngserver.sh: # JRE version: OpenJDK Runtime Environment (8.0_171-b10) (build 1.8.0_171-b10)
May  2 12:50:18 alder fits-ngserver.sh: # Java VM: OpenJDK 64-Bit Server VM (25.171-b10 mixed mode linux-amd64 compressed oops)
May  2 12:50:18 alder fits-ngserver.sh: # Problematic frame:
May  2 12:50:18 alder fits-ngserver.sh: # C  [libzen.so.0.4.37+0x1233d]  ZenLib::File::Read(unsigned char*, unsigned long)+0x4d
May  2 12:50:18 alder fits-ngserver.sh: #
May  2 12:50:18 alder fits-ngserver.sh: # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
May  2 12:50:18 alder fits-ngserver.sh: #
May  2 12:50:18 alder fits-ngserver.sh: # An error report file with more information is saved as:
May  2 12:50:18 alder fits-ngserver.sh: # /tmp/hs_err_pid48810.log
May  2 12:50:18 alder fits-ngserver.sh: #
May  2 12:50:18 alder fits-ngserver.sh: # If you would like to submit a bug report, please visit:
May  2 12:50:18 alder fits-ngserver.sh: #   http://bugreport.java.com/bugreport/crash.jsp
May  2 12:50:18 alder fits-ngserver.sh: # The crash happened outside the Java Virtual Machine in native code.
May  2 12:50:18 alder fits-ngserver.sh: # See problematic frame for where to report the bug.
May  2 12:50:18 alder fits-ngserver.sh: #
May  2 12:50:18 alder systemd: fits-nailgun.service: main process exited, code=killed, status=6/ABRT
May  2 12:50:18 alder systemd: Unit fits-nailgun.service entered failed state.
May  2 12:50:18 alder systemd: fits-nailgun.service failed.
</pre>

CentOS test:

<pre>
[root@mamedin-ffmpeg-ubuntu14 ~]# fits.sh  -i big_buck_bunny_720p_30mb.mkv  -o /tmp/testfits
May 04, 2018 12:30:31 PM edu.harvard.hul.ois.jhove.JhoveBase init
SEVERE: Testing SEVERE level
2018-05-04 12:30:33 - ERROR - ToolBase:286 - Caught Throwable running tool: MediaInfo
java.lang.NullPointerException
	at edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo.reviseIdentification(MediaInfo.java:661)
	at edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo.reviseXmlData(MediaInfo.java:550)
	at edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo.extractInfo(MediaInfo.java:242)
	at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:278)
	at java.lang.Thread.run(Thread.java:748)
</pre>

**Comment by mamedin** [comment]
Copying these files fixes the issue:

https://github.com/harvard-lts/fits/tree/dev/tools/mediainfo/linux

So there are (at least) 2 ways to fix the issue:
- Disable mediainfo at Fits
- Copy these mediainfo files when building the package

**Comment by scollazo** [comment]
After some discussions, we need to disable mediainfo in the rpm build of fits.
