### ISSUE TITLE
Problem: Cannot build Xenial MCPClient package (1.10 and 1.11)

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/am-packbuild#260]
Error:

```
Collecting six==1.13.0 (from -r ./requirements/production.txt (line 25))
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting unidecode==0.04.19 (from -r ./requirements/production.txt (line 26))
  Downloading https://files.pythonhosted.org/packages/5a/73/053be0fafe387d41ce705585412808093f5a333aaa71cabbab641f677c11/Unidecode-0.04.19.tar.gz (204kB)
Collecting urllib3==1.24.3 (from -r ./requirements/production.txt (line 27))
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl (118kB)
Requirement already satisfied: setuptools in ./debian/archivematica-mcp-client/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages (from opf-fido==1.4.1->-r ./requirements/production.txt (line 21))
setuptools requires Python '>=3.5' but the running Python is 2.7.12
You are using pip version 9.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 106, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 86, in main
    deploy.install_dependencies()
  File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 177, in install_dependencies
    subprocess.check_call(self.pip('-r', requirements_path))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/src/src/archivematica/src/MCPClient/debian/archivematica-mcp-client/usr/share/archivematica/virtualenvs/archivematica-mcp-client/bin/python', '/src/src/archivematica/src/MCPClient/debian/archivematica-mcp-client/usr/share/archivematica/virtualenvs/archivematica-mcp-client/bin/pip', 'install', '--log=/tmp/tmp6crR_6', '-r', './requirements.txt']' returned non-zero exit status 1
make[2]: *** [override_dh_virtualenv] Error 1
debian/rules:10: recipe for target 'override_dh_virtualenv' failed
make[2]: Leaving directory '/src/src/archivematica/src/MCPClient'
make[1]: *** [binary] Error 2
debian/rules:7: recipe for target 'binary' failed
make[1]: Leaving directory '/src/src/archivematica/src/MCPClient'
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
```

It happens when building AM1.11 and AM1.10 packages.

**Comment by sevein** [comment]
Fixed by https://github.com/artefactual-labs/am-packbuild/pull/261.
